import turtle
spikey = turtle.Turtle()
sakura = turtle.Turtle()
sakura.shape('turtle')
sakura.color('blue')
sakura.pensize(5)
sakura.left(90)
sakura.left(90)
sakura.forward(100)
sakura.right(90)
sakura.forward(100)
sakura.right(90)
sakura.forward(80)
spikey.shape('turtle')
spikey.color('violet')
spikey.pensize(5)
spikey.forward(100)
spikey.left(90)
spikey.forward(100)
spikey.left(90)
spikey.forward(80)
turtle.done()